name: learn-github-actions
run-name: Testing Binary Caching with Github Actions
on: [push]
jobs:
  build_linux_static:
    name: x64-linux
    runs-on: ubuntu-22.04
    steps:
      - name: CHECK VERSION 
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./vcpkg-exe --version
      - run: cp ./vcpkg-exe vcpkg/vcpkg
      - name: Install Port
        run: |
          ./vcpkg/vcpkg install zlib --binarysource="clear;x-gha,readwrite"

