name: learn-github-actions
run-name: Testing Binary Caching with Github Actions
on: [push]
jobs:
  build_linux_static:
    name: x64-linux
    runs-on: ubuntu-latest
    steps:
      - name: Check Version
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./vcpkg-exe --version
      - name: Export Required Environment Variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - run: cp ./vcpkg-exe vcpkg/vcpkg
      - name: Install 7zip
        run: |
          ./vcpkg/vcpkg install 7zip --binarysource="clear;x-gha,readwrite" --debug